### ISSUE TITLE
How can I get collision_visualization?

### ISSUE THREAD

**Issue by bxc237** [peteflorence/nanomap_ros#3]
HI,
I just tested nanomap after saw your awesome video from CSAIL youtube channel. Thank you for sharing this as open source code! Is that possible to get collision_visualization from nanomap_ros? The bag files you provided in the docker container have it and I think it might be useful for further testing or tuning the nanomap program. And is there any instruction providing more details about integrating nanomap with some planning node (like some planning nodes in ROS navigation stack)? Thanks!

**Comment by peteflorence** [comment]
Glad you've found NanoMap and are trying it out!  I'm also happy to hear you've pulled down the docker container and have got that running.

For the collision_visualization topic, that comes out of this other repo which does stochastic motion-primitives-based motion planning, specifically this function: https://github.com/peteflorence/quadrotor-collision-avoidance/blob/master/src/motion_visualizer.cpp#L47 

The way NanoMap has been used in all of the demos is that the motion planning repo holds on to a NanoMap object, and does both the adding of data (`AddPose()`, `AddPointCloud()`, `AddPoseUpdates()`) into NanoMap and then performs queries into NanoMap (`KnnQuery()`).  I can push up a branch of the other repo that's been integrated with NanoMap. 

Is there a particular ROS planning node that you'd like to see an example of how to integrate it?  NanoMap can work with any sampling-based planner in 2 or 3D like RRT* etc, but not any discrete planner, like 2D A*.

**Comment by bxc237** [comment]
Thank you for your detailed explanation. I think I need to read through your papers about NanoMap and obstacle avoidance to get a better understanding of the structure of the whole system.

Actually, I am trying to find a library that can quickly process the obstacle data in 3D scenario and generate costmap for 2D path planning (a typical way in the default ROS navigation stack). I also tested voxblox before by converting ESDF to local obstacle costmap for planning, which was still not fast enough even when voxel size set to 15cm. Since the default ROS navigation stack using search-based global/local planner(A*, Dijkstra's, DWA), according to your statement, there is no way to integrate NanoMap with them, right?

**Comment by peteflorence** [comment]
Okay, got it.  To quickly get a sense of how NanoMap is different than a discretized, fused mapping representation, I'd recommend watching the technical video, particularly ~20 seconds in: https://www.youtube.com/watch?v=9a0eEscz1Cs

A planner like A* using a discretized map will do graph search optimization where the connections of the graph are based on which voxel/grid cells are next to each other.   NanoMap chooses not to provide a discretized map because we've experienced that type of discretization and fusing to not be a robust way to do mapping in regimes of difficult state estimation (particularly for high speed UAVs).   Note however that A* (or the others) is a general graph search algorithm and for example could be used with NanoMap if instead of discrete cells, the nodes of your graph were motion primitives, and the edges were connecting different concatenations of motion primitives.

Rather than graph search optimization though, the most natural candidates for integration with NanoMap are any sampling-based planners.  RRT*, FMT*, etc -- OMPL has many of these: http://ompl.kavrakilab.org/planners.html

Then again, if you are just doing 2D path planning, and your robot is moving slowly, and you have a good state estimate, you should be OK just using a 2D mapping + 2D planning stack.  Recommend checking out costmap_2d package in ROS, it works just fine.  You can run discrete A*, etc, on that.  Note that you can save a lot of computation by not ever using a full 3D representation. costmap_2d can take in 3D depth sensor measurements, but can insert them into its 2D map, and it's configurable exactly how.  (It can also actually do up to 16 vertical slices, so semi-3D.)  That is a lot cheaper than generating a 3D cost field like VoxBlox would provide.  Note that it's the generating of the cost field that's the real expensive part, rather than just fusing the measurements into voxels.

Also note that the cost-field is usually just "distance to nearest obstacle, for some queried point in space", and NanoMap provides this directly without building up a cost field.  It instead uses a nearest-neighbor query from the k-d-tree of the most recent in-view frame.

Also I'll plug my own master's thesis as a useful reference on all of these topics: https://dspace.mit.edu/handle/1721.1/108982#files-area Chapter 1 (1.3) does some useful review of related work.  In Chapter 3 there's a little bit more detail on how the whole hardware system came together.  In particular note that as described there our UAV actually used 3D local obstacle avoidance, but used just costmap_2d for global planning.

**Comment by bxc237** [comment]
Thank you very much for all this useful information!

 I did try costmap_2d for obstacle avoidance using 16 layers before. But this approach is just not "intelligent" enough, especially if the planning is for a big odd shade robot with some parts of the body are moving. I can, of course, modify the default navigation stack a little and generate multiple 2d costmaps at different height levels that can compute the collision possibility that almost covers the whole robot body and I tried this method as well. Turn out It was slow running on the U series i5 (and actually I do not like the semi 3D way, a robot should perceive the complete scene and adjust its motion based on the perception like the human in the future). Initially, I thought maybe the raytrace marking/clearing mechanism implemented by voxel_grid/octomap/voxblox is the main cause of the speed issue (there are also many other issues like wrong marking/clearing, ghost objects...). That is why I wanted to try NanoMap that seems to use totally different approach to describe and understand (sorry, I might use wrong words) the scene and obstacles around the UAV/robot. But thanks for telling me that actually filling the data in voxels is not the expensive part. So I guess I need to figure out a better way to generate the cost field. And I also like to know compared to the 16 layers 2d costmap approach, according to your experience, is Nanomap still running much faster?

Your master's thesis is really helpful, I will read through. And I'm still interested in trying nanomap on my own robot someday. Thanks again! Close the issue for collision_visualization now.
